### ISSUE TITLE
Run all option

### ISSUE THREAD

**Issue by JoaoPaulo100** [chamberm/Detect#3]
Hi,

First of all, thanks for this great tool!

I'm trying to apply the Inspect script and, based on the main instructions, we could run this for all subjects at once:
_6. If you desire, the Run all option will iterate over all subjects to test them against the healthy controls._

However, I don't see this option ('Run all'). Maybe I'm missing something. I appreciate any guidance you might have.

Thanks!
João Paulo

**Comment by chamberm** [comment]
Hi, sorry for the late reply.
I think this option was removed from the online demo version - but should be there if you install the tool locally!

Best,
Max

**Comment by Loxlan** [comment]
Hi, thanks for the great tool!
I install the tool locally and tried running using the sample data like this:
`python ./Detect/detect.py --i ressources/featuresA.xlsx --demog ressources/demogA.csv`

And got this error:
File "./Detect/detect.py", line 8, in <module>
    import streamlit as st
    
Thanks in advance for any help

Loxlan

**Comment by Loxlan** [comment]
Hi,
Very nice framework!
I just have a quick question on how I can locate/save the data for the reconstructed tract profile? More specifically, how was the data behind the "Fig3. line plots, reconstructed vs typically developing patient" extracted? 

Thanks 
Loxlan Kasa

**Comment by chamberm** [comment]
Hi,

You can either directly save the figures from “Inspect”, Or download the csv file at the end of the page once the analysis is finished. If you have a local version, all images are saved in the directory.

Best,
Max

**Comment by Loxlan** [comment]
Hi Maxime,

Thanks for the quick response.

I do manage to save the figures and the anomaly-vector.csv and p-vals.csv files.
However, what I want to also save is the x_hat (reconstructed tract profile data) when running 'Inspect'.

I do see in the inspect.py lines 168-169 the option for this but it's commented out.

Will appreciate your help on this.

Kind regards,

Loxlan
________________________________

**Comment by chamberm** [comment]
EDIT: just looked at the code and the save method isn’t implemented. What you would have to do i replace the anomaly vector by the x_hat values which should do the trick. 

Ah I see,
Indeed I had to comment those lines because of the online “demo” if I remember correctly.

Did you clone / install the version locally? You could try uncommenting them and let me know. Else I could try adding them again to the main but will need to find time

Max

**Comment by Loxlan** [comment]
Thanks for the reply!

I installed it locally. I've tried running after uncommenting, it throw some errors and stopped.

It will be a great help if you could get it working.

Thanks,
Loxlan
________________________________

**Comment by chamberm** [comment]
I'll see if I can fix that tomorrow or Monday - keep in touch!

**Comment by chamberm** [comment]
Hi, I pushed a fix with the download option at the end of Inspect, let me know if this works!

> Thanks for the reply! I installed it locally. I've tried running after uncommenting, it throw some errors and stopped. It will be a great help if you could get it working. Thanks, Loxlan

**Comment by Loxlan** [comment]
Awesome, thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chamberm** [comment]
Closed
